"""
REPLAY BUFFER for real environment transitions 

STORES HRVQ TOKENS 

Used for:
    1. Training RewardNetwork and ContinueNetwork (supervised, real labels)
    2. Seeding imagination rollouts (context windows)
    3. Training WORLD MODEL in joint mode (token sequences)             

NOT for imagined trajectories (those are generated by world model)
"""

import torch
import numpy as np
from typing import Dict, Optional

class TokenReplayBuffer:
    """
    Fixed-capacity ring buffer for HRVQ token transitions.
    
    Stores individual timesteps, returns sequences of length seq_len.
    Pre-allocated tensors for memory efficiency.
    """
    
    def __init__(
        self,
        capacity : int = 100_000,
        seq_len  : int = 64,
        device   : torch.device = None,
    ):
        self.capacity = capacity
        self.seq_len = seq_len
        self.device = device or torch.device('cpu')
        
        # PRE ALLOCATE STORAGE (On CPU to save GPU memory)
        self._tokens = torch.zeros(capacity, 3, dtype=torch.long)     # HRVQ [L0, L1, L2]
        self._actions = torch.zeros(capacity, dtype=torch.long)       # Action indices
        self._rewards = torch.zeros(capacity, dtype=torch.float32)    # Rewards
        self._dones = torch.zeros(capacity, dtype=torch.bool)         # Done flags
        
        # Ring buffer pointers
        self._ptr = 0
        self._size = 0
    
    def push(
        self,
        tokens : torch.Tensor,   # (3,) int64
        action : int,
        reward : float,
        done   : bool,
    ):
        """Store single transition."""
        self._tokens[self._ptr] = tokens
        self._actions[self._ptr] = action
        self._rewards[self._ptr] = reward
        self._dones[self._ptr] = done
        
        # Update ring buffer pointers
        self._ptr = (self._ptr + 1) % self.capacity
        self._size = min(self._size + 1, self.capacity)
    
    def push_batch(
        self,
        tokens  : torch.Tensor,   # (N, 3)
        actions : torch.Tensor,  # (N,)
        rewards : torch.Tensor,  # (N,)
        dones   : torch.Tensor,    # (N,)
    ):
        """Store batch of transitions."""
        N = tokens.size(0)
        for i in range(N):
            self.push(tokens[i], actions[i].item(), rewards[i].item(), dones[i].item())
            
    def _build_sequence_indices(
        self,
        start_indices : torch.Tensor,  # (B,) int64
        length        : int,
    ) -> torch.Tensor:
        """ VECTORISED: Replaces [self._tokens[s:s + self.seq_len] for s in start_indices] with a single gather operation. """
        
        offsets = torch.arange(length, dtype = torch.long)           # (L, )
        indices = start_indices.unsqueeze(1) + offsets.unsqueeze(0)  # (B, L)
        return indices

    def sample(
        self,
        batch_size : int,
    ) -> Dict[str, torch.Tensor]:
        """Sample random sequences of length seq_len from the buffer.
        
        FOR RewardNetwork and ContinueNetwork training 
        (supervised learning on real data).
        """
        
        assert self._size >= self.seq_len, "BUFFER TOO SMALL FOR SAMPLING SEQUENCES"
        
        # Find valid start indices (no wrapping around pointer, no crossing capacity)
        max_start = self._size - self.seq_len
        if max_start <= 0:
            raise ValueError("Not enough data to sample sequences")
        
        start_indicies = torch.randint(0, max_start, (batch_size,))
        
        
        
        # VECTORISED GATHERING OF SEQUENCES (REPLACES LIST COMPREHENSION)
        
        indices = self._build_sequence_indices(start_indices = start_indicies, length = self.seq_len)  # (B, L)
        
        tokens_batch = self._tokens[indices].to(self.device)  # (B, seq_len, 3)
        actions_batch = self._actions[indices].to(self.device)  # (B, seq_len)
        rewards_batch = self._rewards[indices].to(self.device)  # (B, seq_len)
        dones_batch = self._dones[indices].to(self.device)  # (B, seq_len)
        
        return {
            'tokens'    : tokens_batch,   # (B, seq_len, 3)
            'actions'   : actions_batch, # (B, seq_len)
            'rewards'   : rewards_batch, # (B, seq_len)
            'dones'     : dones_batch,     # (B, seq_len)
        }
        
        
        # OLD LIST COMPREHENSION for GATHERING SEQUENCES
        tokens_batch = torch.stack([
            self._tokens[s:s + self.seq_len] for s in start_indicies
        ]).to(self.device)  # (B, L, 3)
        
        actions_batch = torch.stack([
            self._actions[s:s + self.seq_len] for s in start_indicies
        ]).to(self.device)  # (B, L)
        
        rewards_batch = torch.stack([
            self._rewards[s:s + self.seq_len] for s in start_indicies
        ]).to(self.device)  # (B, L)
        
        dones_batch = torch.stack([
            self._dones[s:s + self.seq_len] for s in start_indicies 
        ]).to(self.device)  # (B, L)
        
        # RETURN AS DICTIONARY
        return {
            'tokens'    : tokens_batch,   # (B, L, 3)
            'actions'   : actions_batch, # (B, L)
            'rewards'   : rewards_batch, # (B, L)
            'dones'     : dones_batch,     # (B, L)
        }

    def sample_seed_context(
        self,
        batch_size  : int,
        context_len : int = 16, # Explore 32, 64 (LONGER CONTEXTS)
    ) -> Dict[str, torch.Tensor]:
        """Sample short context window for seeding imagination.
        (TOKENS + ACTIONS, NO REWARDS OR DONES)
        
        FOR Imagination Seeding (context windows for world model rollouts)
        """
        
        max_start = self._size - context_len
        if max_start <= 0:
            max_start = 1
        
        start_indicies = torch.randint(0, max_start, (batch_size,))
        
        # VECTORISED GATHERING OF SEQUENCES (REPLACES LIST COMPREHENSION)
        
        indices = self._build_sequence_indices(start_indices = start_indicies, length = context_len)  # (B, context_len)

        tokens = self._tokens[indices].to(self.device)  # (B, context_len, 3)
        actions = self._actions[indices].to(self.device)  # (B, context_len)
        
        return {
            'tokens' : tokens,   # (B, context_len, 3)
            'actions' : actions, # (B, context_len)
        }
        
        # OLD LIST COMPREHENSION for GATHERING SEQUENCES (ONLY TOKENS AND ACTIONS, NO REWARDS OR DONES)
        tokens = torch.stack([
            self._tokens[s:s + context_len] for s in start_indicies
        ]).to(self.device)  # (B, context_len, 3)
        
        actions = torch.stack([
            self._actions[s:s + context_len] for s in start_indicies    
        ]).to(self.device)  # (B, context_len)
        
        return {'tokens' : tokens, 'actions' : actions}
    
    def sample_reward_biased_seed(
        self,
        batch_size  : int,
        context_len : int = 16,
        nonzero_fraction : float = 0.5,
    ) -> Dict[str, torch.Tensor]:
        """Sample seed contexts with half from near non-zero reward events.

        WHY: 99% of Pong timesteps have reward=0. Pure random seeding means
        ~86% of 15-step imagination rollouts contain zero reward, giving no actor
        gradient. Oversampling near-reward states ensures imagined trajectories
        actually contain the scoring events the policy needs to learn from.

        nonzero_fraction: fraction of batch seeded from near-reward events.
                          The rest are random (prevents overfitting to rare events).
        """
        # Find all timesteps with non-zero reward
        nonzero_idx = torch.where(self._rewards[:self._size].abs() > 1e-4)[0]

        nonzero_n = int(batch_size * nonzero_fraction) if len(nonzero_idx) > 0 else 0
        random_n  = batch_size - nonzero_n

        parts = []

        if nonzero_n > 0:
            # Pick random reward events, then back up so the reward falls
            # near the END of the context window (the WM can see lead-up)
            chosen = nonzero_idx[torch.randint(len(nonzero_idx), (nonzero_n,))]
            # Place reward ~75% through context so rollout can reach it quickly
            offset = max(1, int(context_len * 0.75))
            starts = (chosen.long() - offset).clamp(0, self._size - context_len)
            parts.append(starts)

        if random_n > 0:
            max_start = max(1, self._size - context_len)
            parts.append(torch.randint(0, max_start, (random_n,)))

        start_indices = torch.cat(parts, dim=0)[:batch_size]

        indices = self._build_sequence_indices(start_indices, context_len)
        tokens  = self._tokens[indices].to(self.device)   # (B, context_len, 3)
        actions = self._actions[indices].to(self.device)  # (B, context_len)

        return {'tokens': tokens, 'actions': actions}

    def sample_wm_batch(
        self,
        batch_size : int,
        seq_len    : int = 64,
    ) -> Dict[str, torch.Tensor]:
        """Sample TOKEN + ACTION sequences for WORLD MODEL TRAINING (joint mode).
        
        Similar to sample(), but can be used for training the world model on real data.
        """

        # CHECK ENOUGH DATA FOR SAMPLING SEQUENCES
        assert self._size >= seq_len, (
            f"Buffer has {self._size} transitions but WM needs seq_len={seq_len}"
        )

        # CHECK VALID START INDICES (NO WRAPPING AROUND POINTER, NO CROSSING CAPACITY)
        max_start = self._size - seq_len
        if max_start <= 0:
            raise ValueError(
                f"Not enough data for WM batch: need {seq_len}, have {self._size}"
        )

        start_indicies = torch.randint(0, max_start, (batch_size,))

        # VECTORISED GATHERING OF SEQUENCES (REPLACES LIST COMPREHENSION)
        indices = self._build_sequence_indices(start_indices = start_indicies, length = seq_len)  # (B, seq_len)
        tokens_batch = self._tokens[indices].to(self.device)  # (B, seq_len, 3)
        actions_batch = self._actions[indices].to(self.device)  # (B, seq_len)  

        return {
            'tokens' : tokens_batch,   # (B, seq_len, 3)
            'actions' : actions_batch, # (B, seq_len)
        }

        # OLD LIST COMPREHENSION for GATHERING SEQUENCES (ONLY TOKENS AND ACTIONS, NO REWARDS OR DONES)

        tokens_batch = torch.stack([
            self._tokens[s:s + seq_len] for s in start_indicies
        ]).to(self.device)  # (B, seq_len, 3)

        actions_batch = torch.stack([
            self._actions[s:s + seq_len] for s in start_indicies
        ]).to(self.device)  # (B, seq_len)

        # RETURN AS DICTIONARY
        return {
            'tokens' : tokens_batch,   # (B, seq_len, 3)
            'actions' : actions_batch, # (B, seq_len)
        }
        

    def __len__(self) -> int:
        return self._size
    
    def is_ready(
        self,
        min_size : int = 1000,
    ) -> bool: 
        """Check if buffer has enough data for sampling sequences."""
        return self._size >= min_size
    
    @classmethod
    def from_numpy_data(  
        cls,
        tokens_dir       : str,
        replay_dir       : str,
        game             : str,
        capacity         : int = 100_000,
        seq_len          : int = 64,
        device           : torch.device = None,
    ):
        """ CREATE and PREPOPULATE BUFFER from numpy arrays (EXISTING PRE-EXTRACTED TOKEN FILES) """
        
        buffer = cls(capacity = capacity, seq_len = seq_len, device = device)
        
        # LOAD HRVQ Tokens (Stacked L0, L1, L2)
        layers = []
        for layer in range(3):
            path = f"{tokens_dir}/vq_tokens_ALE_{game}_layer{layer}.npy"
            
            t = np.load(path).squeeze()  # (T,)
            layers.append(t)
        
        tokens = np.stack(layers, axis=1).astype(np.int64)  # (T, 3)
        
        # LOAD Actions and Rewards from replay buffer
        replay = np.load(f"{replay_dir}/replay_buffer_ALE_{game}.npz")
        
        actions = replay['actions'].astype(np.int64)    # (T,)
        rewards = replay['rewards'].astype(np.float32)  # (T,)
        dones = replay['dones']                         # (T,)
        
        # PUSH ALL DATA INTO BUFFER
        N = min(len(tokens), len(actions), len(rewards), len(dones), capacity)
        
        # CONVERT TO RAW INTEGER TENSORS AND PUSH
        buffer._tokens[:N] = torch.from_numpy(tokens[:N])
        buffer._actions[:N] = torch.from_numpy(actions[:N])
        buffer._rewards[:N] = torch.from_numpy(rewards[:N])
        buffer._dones[:N] = torch.from_numpy(dones[:N])
        
        buffer._size = N
        buffer._ptr = N % capacity
        
        print(f"    Loaded {N} transitions for {game}")
        return buffer