"""
REPLAY BUFFER for real environment transitions 

STORES HRVQ TOKENS 

Used for:
    1. Training RewardNetwork and ContinueNetwork (supervised, real labels)
    2. Seeding imagination rollouts (context windows)

NOT for imagined trajectories (those are generated by world model)
"""

import torch
import numpy as np
from typing import Dict, Optional

class TokenReplayBuffer:
    """
    Fixed-capacity ring buffer for HRVQ token transitions.
    
    Stores individual timesteps, returns sequences of length seq_len.
    Pre-allocated tensors for memory efficiency.
    """
    
    def __init__(
        self,
        capacity : int = 100_000,
        seq_len : int = 64,
        device : torch.device = None,
    ):
        self.capacity = capacity
        self.seq_len = seq_len
        self.device = device or torch.device('cpu')
        
        # PRE ALLOCATE STORAGE (On CPU to save GPU memory)
        self._tokens = torch.zeros(capacity, 3, dtype=torch.long)     # HRVQ [L0, L1, L2]
        self._actions = torch.zeros(capacity, dtype=torch.long)       # Action indices
        self._rewards = torch.zeros(capacity, dtype=torch.float32)    # Rewards
        self._dones = torch.zeros(capacity, dtype=torch.bool)         # Done flags
        
        # Ring buffer pointers
        self._ptr = 0
        self._size = 0
    
    def push(
        self,
        tokens : torch.Tensor,   # (3,) int64
        action : int,
        reward : float,
        done : bool,
    ):
        """Store single transition."""
        self._tokens[self._ptr] = tokens
        self._actions[self._ptr] = action
        self._rewards[self._ptr] = reward
        self._dones[self._ptr] = done
        
        # Update ring buffer pointers
        self._ptr = (self._ptr + 1) % self.capacity
        self._size = min(self._size + 1, self.capacity)
    
    def push_batch(
        self,
        tokens : torch.Tensor,   # (N, 3)
        actions : torch.Tensor,  # (N,)
        rewards : torch.Tensor,  # (N,)
        dones : torch.Tensor,    # (N,)
    ):
        """Store batch of transitions."""
        N = tokens.size(0)
        for i in range(N):
            self.push(tokens[i], actions[i].item(), rewards[i].item(), dones[i].item())
    
    def sample(
    ):
        """Sample random sequences of length seq_len from the buffer."""
        pass

    def sample_seed_context(
    ):
        """Sample short context window for seeding imagination."""
        pass
    
    def __len__(self) -> int:
        return self._size
    
    def is_ready(self): 
        """Check if buffer has enough data for sampling sequences."""
        pass
    
    @classmethod
    def from_numpy_data(  
    ):
        """ Pre-populate buffer from numpy arrays (EXISTING PRE-EXTRACTED TOKEN FILES) """
        pass
    